<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Autoevaluacion" nsURI="Autoevaluacion" nsPrefix="Autoevaluacion">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore#/"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Hoja">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nonEmptyStyle"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="nonEmptyStyle" value="&#xA;&#x9;&#x9;    not estilo.oclIsUndefined() &#xA;&#x9;&#x9;    and estilo &lt;> ''"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nota" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ejercicios" upperBound="-1"
        eType="#//Ejercicio" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="estilo" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ejercicio">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nonEmptyName nonEmptyEnun"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="nonEmptyName" value="&#xA;&#x9;&#x9;    not name.oclIsUndefined() &#xA;&#x9;&#x9;    and name &lt;> ''"/>
      <details key="nonEmptyEnun" value="&#xA;&#x9;&#x9;    not enunciado.oclIsUndefined()&#xA;&#x9;&#x9;    and enunciado &lt;> ''"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enunciado" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="puntuacion" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="respuestas" lowerBound="1"
        eType="#//Respuestas" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tematica" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Respuestas" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="correctas" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alternativas" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seleccionadas" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RespuestaUnica" eSuperTypes="#//Respuestas">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="uniqueAnswer"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="uniqueAnswer" value="&#xA;&#x9;&#x9;&#x9;correctas->size()=1"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RespuestaMultiple" eSuperTypes="#//Respuestas"/>
  <eClassifiers xsi:type="ecore:EClass" name="TextoLibre" eSuperTypes="#//Respuestas">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="posibleAnswers"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="posibleAnswers" value="&#xA;&#x9;&#x9;&#x9;correctas->size()>0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ordenacion" eSuperTypes="#//Respuestas">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="uniqueAnswer"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="uniqueAnswer" value="&#xA;&#x9;&#x9;&#x9;correctas->size()=1"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
